### ISSUE TITLE
option to fix localhost:port

### ISSUE THREAD

**Issue by chscho** [gexijin/RTutor#45]
Hi Steven

Thank you for developing such a cool tool! I'd like to implement it in my research group and therefore install it on one of our servers. To access the site I would do an ssh-tunnel, which allows everybody from my group to access the tool in their own browser.
The problem with that is, that 
`run_app(port=1234)` 
does not influence the selected port for the shiny app and hence the tunneling only works, if it is always updated to the currently active port. Is there a way to fix the port upon startup of Rtutor? So far I was not able to find such a config file...

Thank you in advance for your help!

Best,
Christian

**Comment by gexijin** [comment]
Hi Christian,
Try this, I am not sure if it will help.
```
options(shiny.port = 1234)
run_app()
```
Also, my server configuration is here https://github.com/gexijin/RTutor_server
It is not documented but I use docker-compose to define a load balancer and some containers. 

Since there are a few more question about containers, I will look into it and provide more documentation.

**Comment by chscho** [comment]
Hi Steven

Thank you for your quick support. This will do it for the moment...  Depending on the usage by my team I might switch to a server-based solution at a later time point.

Best,
Christian
